services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.6
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory-lock=true
      - xpack.security.enabled=false
      - xpack.ecurity.audit.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-network
      - logging

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.17.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports: 
      - "5601:5601"
    networks: 
      - app-network
      - logging
    depends_on: 
      - elasticsearch

  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:8.17.4
    environment: 
      - 
    volumes:
      - 
    ports:
      - "5044:5044"
    networks:
      - app-network
      - logging
    depends_on:
      - elasticsearch

volumes:
  elasticsearch-data:

networks:
  app-network:
    external: True

  logging:
    name: logging
