services: 
  app:
    container_name: app 
    build: .
    ports:
      - "5001:5000"
    depends_on:
      - redis
  redis:
    container_name: redis
    image: "redis:alpine"
    ports: 
      - "6379:6379"
